Data Science Fundamentals: Python |
[Table of Contents](../index.ipynb)
- - - 
<!--NAVIGATION-->
Module 9. | [Introduction to NumPy](./01_introduction_NumPy.ipynb) | **[The Basics](./02_basics_NumPy.ipynb)** | [Exercises](./03_NumPy_exercises.ipynb) | [Tutorial](./05_NumPy_Tutorial.ipynb)

# NumPy Basics

In [10]:
from IPython.display import HTML

# Youtube
HTML('<iframe width="560" height="315" src="https://www.youtube.com/embed/QUT1VHiLmmI?rel=0&amp;controls=0&amp;showinfo=0" frameborder="0" allowfullscreen></iframe>')


NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called axes.

For example, the coordinates of a point in 3D space [1, 2, 1] has one axis. That axis has 3 elements in it, so we say it has a length of 3. In the example pictured below, the array has 2 axes. The first axis has a length of 2, the second axis has a length of 3.

In [11]:
import numpy as np

NumPy’s array class is called ndarray. It is also known by the alias array. Note that numpy.array is not the same as the Standard Python Library class array.array, which only handles one-dimensional arrays and offers less functionality. The more important attributes of an ndarray object are:

```
ndarray.ndim 

the number of axes (dimensions) of the array.
```

```
ndarray.shape

the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes, ndim.
```

```
ndarray.size

the total number of elements of the array. This is equal to the product of the elements of shape.
```

```
ndarray.dtype

an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. Additionally NumPy provides types of its own. numpy.int32, numpy.int16, and numpy.float64 are some examples.
```

```
ndarray.itemsize

the size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8 (=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.
```

```
ndarray.data

the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.
```

### An Example

In [12]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
a.shape

(3, 5)

In [14]:
a.ndim

2

In [15]:
a.dtype.name

'int32'

In [16]:
a.itemsize

4

In [17]:
a.size

15

In [18]:
type(a)

numpy.ndarray

In [19]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [20]:
type(b)

numpy.ndarray

In [21]:
b.size

3

In [22]:
b.shape

(3,)

In [28]:
b.ndim

1

### Array Creation

There are several ways to create arrays.

For example, you can create an array from a regular Python list or tuple using the array function. The type of the resulting array is deduced from the type of the elements in the sequences.

In [23]:
import numpy as np
a = np.array([2,3,4])
a

array([2, 3, 4])

In [24]:
a.dtype

dtype('int32')

In [25]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

A frequent error consists in calling array with multiple arguments, rather than providing a single sequence as an argument.

In [26]:
a = np.array(1,2,3,4)    # WRONG

ValueError: only 2 non-keyword arguments accepted

In [29]:
a = np.array([1,2,3,4])  # RIGHT

array transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.

In [32]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

The type of the array can also be explicitly specified at creation time:

In [33]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive operation.

The function `zeros` creates an array full of zeros, the function `ones` creates an array full of ones, and the function `empty` creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is float64.

In [34]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
np.ones( (2,3,4), dtype=np.int16 )                # dtype can also be specified

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [38]:
np.empty((4,3))                                 # uninitialized

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

To create sequences of numbers, NumPy provides the `arange` function which is analogous to the Python built-in `range`, but returns an array.

In [39]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [40]:
np.arange( 0, 2, 0.3 )                 # it accepts float arguments

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

When arange is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function linspace that receives as an argument the number of elements that we want, instead of the step:

In [41]:
from numpy import pi
np.linspace( 0, 2, 9 )                 # 9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [44]:
x = np.linspace( 0, 2*pi, 100 )        # useful to evaluate function at lots of points
f = np.sin(x)
f

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

### Printing Arrays

When you print an array, NumPy displays it in a similar way to nested lists, but with the following layout:

- the last axis is printed from left to right,
- the second-to-last is printed from top to bottom,
- the rest are also printed from top to bottom, with each slice separated from the next by an empty line.

One-dimensional arrays are then printed as rows, bidimensionals as matrices and tridimensionals as lists of matrices.

In [45]:
a = np.arange(6)                         # 1d array
print(a)

[0 1 2 3 4 5]


In [46]:
b = np.arange(12).reshape(4,3)           # 2d array
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [47]:
c = np.arange(24).reshape(2,3,4)         # 3d array
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


See below to get more details on reshape.

If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the corners:

In [48]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [51]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


To disable this behaviour and force NumPy to print the entire array, you can change the printing options using set_printoptions.

In [58]:
import sys
np.set_printoptions(threshold=sys.maxsize)       # sys module should be imported

In [59]:
print(np.arange(10000).reshape(100,100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


### Basic Operations

Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [60]:
a = np.array( [20,30,40,50] )
b = np.arange(4)
b

array([0, 1, 2, 3])

In [61]:
c = a-b
c

array([20, 29, 38, 47])

In [62]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [63]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

![trig_formulas](files/trig_formulas.png)

In [64]:
a<35

array([ True,  True, False, False])

Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays. The matrix product can be performed using the @ operator (in python >=3.5) or the dot function or method:

In [68]:
A = np.array( [[1,1],
              [0,1]] )
B = np.array( [[2,0],
              [3,4]] )
A * B                       # elementwise product     

array([[2, 0],
       [0, 4]])

Matrix multiplication is an operation that takes two matrices as input and produces single matrix by multiplying rows of the first matrix to the column of the second matrix.In matrix multiplication make sure that the number of rows of the first matrix should be equal to the number of columns of the second matrix.

Example: Multiplication of two matrices by each other of size 3×3.

In [69]:
A @ B                       # matrix product

array([[5, 4],
       [3, 4]])

In [70]:
A.dot(B)                    # another matrix product

array([[5, 4],
       [3, 4]])

Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.

In [71]:
rg = np.random.default_rng(1)     # create instance of default random number generator
a = np.ones((2,3), dtype=int)
b = rg.random((2,3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [72]:
b += a
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

In [73]:
a += b                            # b is not automatically converted to integer type

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as **upcasting**).

In [75]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,pi,3)
b.dtype.name

'float64'

In [78]:
c = a+b
c

array([1.        , 2.57079633, 4.14159265])

In [79]:
c.dtype.name

'float64'

In [80]:
d = np.exp(c*1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [81]:
d.dtype.name

'complex128'

Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class.

**What does unary operation mean?**

In mathematics, a unary operation is an operation with only one operand, i.e. a single input. This is in contrast to binary operations, which use two operands. An example is the function f : A → A, where A is a set. The function f is a unary operation on A.

In [82]:
a = rg.random((2,3))
a

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [83]:
a.sum()

3.1057109529998157

In [84]:
a.min()

0.027559113243068367

In [85]:
a.max()

0.8277025938204418

By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the axis parameter you can apply an operation along the specified axis of an array:

In [86]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [87]:
b.sum(axis=0)                            # sum of each column

array([12, 15, 18, 21])

In [88]:
 b.min(axis=1)                            # min of each row

array([0, 4, 8])

In [89]:
 b.cumsum(axis=1)                         # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

### Universal Functions

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

![trig_formulas](files/trig_formulas.png)

In [90]:
B = np.arange(3)
B

array([0, 1, 2])

In [91]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [92]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [94]:
C = np.array([2., -1., 4.])

In [95]:
np.add(B, C)

array([2., 0., 6.])

### Indexing, Slicing, Iterating

One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

In [96]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [97]:
a[2]

8

In [98]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [99]:
# equivalent to a[0:6:2] = 1000;
# from start to position 6, exclusive, set every 2nd element to 1000
a[:6:2] = 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729],
      dtype=int32)

In [100]:
a[ : :-1]                                 # reversed a

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000],
      dtype=int32)

In [101]:
for i in a:
         print(i**(1/3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas:

In [107]:
def f(x,y):
    return 10*x+y

In [108]:
b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [104]:
b[2,3]

23

In [109]:
b[0:5, 1]                       # each row in the second column of b

array([ 1, 11, 21, 31, 41])

In [110]:
b[ : ,1]                        # equivalent to the previous example

array([ 1, 11, 21, 31, 41])

In [111]:
b[1:3, : ]                      # each column in the second and third row of b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

When fewer indices are provided than the number of axes, the missing indices are considered complete slices:

In [112]:
b[-1]                                  # the last row. Equivalent to b[-1,:]

array([40, 41, 42, 43])

The expression within brackets in b[i] is treated as an i followed by as many instances of : as needed to represent the remaining axes. NumPy also allows you to write this using dots as b[i,...].

The dots (...) represent as many colons as needed to produce a complete indexing tuple. For example, if x is an array with 5 axes, then
```
- x[1,2,...] is equivalent to x[1,2,:,:,:],
- x[...,3] to x[:,:,:,:,3] and
- x[4,...,5,:] to x[4,:,:,5,:].
```

NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [113]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [114]:
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                [ 10, 12, 13]],
                [[100,101,102],
                [110,112,113]]])

In [115]:
c.shape

(2, 2, 3)

In [116]:
 c[1,...]                                   # same as c[1,:,:] or c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [117]:
c[...,2]                                   # same as c[:,:,2]

array([[  2,  13],
       [102, 113]])

Iterating over multidimensional arrays is done with respect to the first axis:

In [118]:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [119]:
for row in c:
    print(row)

[[ 0  1  2]
 [10 12 13]]
[[100 101 102]
 [110 112 113]]


However, if one wants to perform an operation on each element in the array, one can use the flat attribute which is an iterator over all the elements of the array:

In [120]:
for element in b.flat:
    print(element)
  # print(element*2)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


### Shape Manipulation

#### Changing the shape of an array

**What is the shape of an array?**

Shape is a tuple that gives you an indication of the number of dimensions in the array. So in your case, since the index value of Y. shape[0] is 0, your are working along the first dimension of your array.

An array has a shape given by the number of elements along each axis:

In [121]:
a = np.floor(10*rg.random((3,4)))
a

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

In [122]:
a.shape

(3, 4)

The shape of an array can be changed with various commands. Note that the following three commands all return a modified array, but do not change the original array:

In [123]:
a.ravel()  # returns the array, flattened

array([3., 7., 3., 4., 1., 4., 2., 2., 7., 2., 4., 9.])

In [124]:
a.reshape(6,2)  # returns the array with a modified shape

array([[3., 7.],
       [3., 4.],
       [1., 4.],
       [2., 2.],
       [7., 2.],
       [4., 9.]])

In [125]:
a.T  # returns the array, transposed

array([[3., 1., 7.],
       [7., 4., 2.],
       [3., 2., 4.],
       [4., 2., 9.]])

In [126]:
a.T.shape

(4, 3)

In [127]:
a.shape

(3, 4)

The order of the elements in the array resulting from ravel() is normally “C-style”, that is, the rightmost index “changes the fastest”, so the element after a[0,0] is a[0,1]. If the array is reshaped to some other shape, again the array is treated as “C-style”. NumPy normally creates arrays stored in this order, so ravel() will usually not need to copy its argument, but if the array was made by taking slices of another array or created with unusual options, it may need to be copied. The functions ravel() and reshape() can also be instructed, using an optional argument, to use FORTRAN-style arrays, in which the leftmost index changes the fastest.

![numpy cheatsheet](files/numpy_cheatsheet.png)

The reshape function returns its argument with a modified shape, whereas the ndarray.resize method modifies the array itself:

In [128]:
a

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

In [129]:
a.resize((2,6))

In [130]:
a

array([[3., 7., 3., 4., 1., 4.],
       [2., 2., 7., 2., 4., 9.]])

If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:

**How does the reshape function work?**

The reshape() function is used to give a new shape to an array without changing its data.
<br>
![numpy.reshape](files/numpy-manipulation-reshape-function-image-a.png)

In [131]:
a.reshape(3,-1)

array([[3., 7., 3., 4.],
       [1., 4., 2., 2.],
       [7., 2., 4., 9.]])

### Stacking together different arrays

Several arrays can be stacked together along different axes:

In [132]:
a = np.floor(10*rg.random((2,2)))
a

array([[9., 7.],
       [5., 2.]])

In [133]:
b = np.floor(10*rg.random((2,2)))
b

array([[1., 9.],
       [5., 1.]])

In [134]:
np.vstack((a,b))

array([[9., 7.],
       [5., 2.],
       [1., 9.],
       [5., 1.]])

In [135]:
np.hstack((a,b))

array([[9., 7., 1., 9.],
       [5., 2., 5., 1.]])

The function column_stack stacks 1D arrays as columns into a 2D array. It is equivalent to hstack only for 2D arrays:

In [136]:
from numpy import newaxis
np.column_stack((a,b))     # with 2D arrays

array([[9., 7., 1., 9.],
       [5., 2., 5., 1.]])

In [137]:
a = np.array([4.,2.])
b = np.array([3.,8.])
np.column_stack((a,b))     # returns a 2D array

array([[4., 3.],
       [2., 8.]])

In [138]:
np.hstack((a,b))           # the result is different

array([4., 2., 3., 8.])

In [139]:
a[:,newaxis]               # view `a` as a 2D column vector

array([[4.],
       [2.]])

In [140]:
np.column_stack((a[:,newaxis],b[:,newaxis]))

array([[4., 3.],
       [2., 8.]])

In [141]:
np.hstack((a[:,newaxis],b[:,newaxis]))   # the result is the same

array([[4., 3.],
       [2., 8.]])

On the other hand, the function row_stack is equivalent to [vstack](https://numpy.org/devdocs/reference/generated/numpy.vstack.html#numpy.vstack) for any input arrays. In fact, row_stack is an alias for [vstack](https://numpy.org/devdocs/reference/generated/numpy.vstack.html#numpy.vstack):

In [142]:
np.column_stack is np.hstack

False

In [143]:
np.row_stack is np.vstack

True

In general, for arrays with more than two dimensions, hstack stacks along their second axes, vstack stacks along their first axes, and concatenate allows for an optional arguments giving the number of the axis along which the concatenation should happen.

***Note***

In complex cases, r_ and c_ are useful for creating arrays by stacking numbers along one axis. They allow the use of range literals (“:”)

In [144]:
np.r_[1:4,0,4]

array([1, 2, 3, 0, 4])

When used with arrays as arguments, r_ and c_ are similar to [vstack](https://numpy.org/devdocs/reference/generated/numpy.vstack.html#numpy.vstack) and [hstack](https://numpy.org/devdocs/reference/generated/numpy.hstack.html#numpy.hstack) in their default behavior, but allow for an optional argument giving the number of the axis along which to concatenate.

![numpy.stack](files/numpy_cheatsheet3.png)

### Splitting One Array Into Several Small Ones

Using [hsplit](https://numpy.org/devdocs/reference/generated/numpy.hsplit.html#numpy.hsplit), you can split an array along its horizontal axis, either by specifying the number of equally shaped arrays to return, or by specifying the columns after which the division should occur:

In [145]:
a = np.floor(10*rg.random((2,12)))
a

array([[6., 7., 6., 9., 0., 5., 4., 0., 6., 8., 5., 2.],
       [8., 5., 5., 7., 1., 8., 6., 7., 1., 8., 1., 0.]])

In [146]:
# Split a into 3
np.hsplit(a,3)

[array([[6., 7., 6., 9.],
        [8., 5., 5., 7.]]),
 array([[0., 5., 4., 0.],
        [1., 8., 6., 7.]]),
 array([[6., 8., 5., 2.],
        [1., 8., 1., 0.]])]

In [147]:
# Split a after the third and the fourth column
np.hsplit(a,(3,4))

[array([[6., 7., 6.],
        [8., 5., 5.]]),
 array([[9.],
        [7.]]),
 array([[0., 5., 4., 0., 6., 8., 5., 2.],
        [1., 8., 6., 7., 1., 8., 1., 0.]])]

[vsplit](https://numpy.org/devdocs/reference/generated/numpy.vsplit.html#numpy.vsplit) splits along the vertical axis, and [array_split](https://numpy.org/devdocs/reference/generated/numpy.array_split.html#numpy.array_split) allows one to specify along which axis to split.

### Copies and Views

When operating and manipulating arrays, their data is sometimes copied into a new array and sometimes not. This is often a source of confusion for beginners. There are three cases:

#### No Copy At All

Simple assignments make no copy of objects or their data.

In [148]:
a = np.array([[ 0,  1,  2,  3],
            [ 4,  5,  6,  7],
            [ 8,  9, 10, 11]])
b = a            # no new object is created
b is a           # a and b are two names for the same ndarray object

True

Python passes mutable objects as references, so function calls make no copy.

In [149]:
def f(x):
    print(id(x))

id(a)                           # id is a unique identifier of an object

1555175922624

In [150]:
f(a)

1555175922624


#### View Or Shallow Copy

Different array objects can share the same data. The view method creates a new array object that looks at the same data.

In [151]:
c = a.view()
c is a

False

In [152]:
c.base is a                     # c is a view of the data owned by a

True

In [153]:
c.flags.owndata

False

In [154]:
c = c.reshape((2, 6))                      # a's shape doesn't change
a.shape

(3, 4)

In [155]:
c[0, 4] = 1234                      # a's data changes
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

Slicing an array returns a view of it:

In [156]:
s = a[ : , 1:3]     # spaces added for clarity; could also be written "s = a[:, 1:3]"
s[:] = 10           # s[:] is a view of s. Note the difference between s = 10 and s[:] = 10
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

#### Deep Copy

The copy method makes a complete copy of the array and its data.

In [157]:
d = a.copy()                          # a new array object with new data is created
d is a

False

In [158]:
d.base is a                           # d doesn't share anything with a

False

In [159]:
d[0,0] = 9999
a

array([[   0,   10,   10,    3],
       [1234,   10,   10,    7],
       [   8,   10,   10,   11]])

Sometimes copy should be called after slicing if the original array is not required anymore. For example, suppose a is a huge intermediate result and the final result b only contains a small fraction of a, a deep copy should be made when constructing b with slicing:

In [161]:
a = np.arange(int(1e8))
b = a[:100].copy()
del a  # the memory of ``a`` can be released.

If b = a[:100] is used instead, a is referenced by b and will persist in memory even if del a is executed.

- - -
[See Real World Examples of using NumPy](https://github.com/neozhaoliang/pywonderland)

- - - 
<!--NAVIGATION-->
Module 9. | [Introduction to NumPy](./01_introduction_NumPy.ipynb) | **[The Basics](./02_basics_NumPy.ipynb)** | [Exercises](./03_NumPy_exercises.ipynb)
<br>
[Top](#)

- - -

Copyright © 2020 Qualex Consulting Services Incorporated.